### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MRslimcoder**

### CODE REVIEW

**Review by CodingSpecies — APPROVED** [review]
LGTM @MRslimcoder

**Comment by AvidCoder101** [comment]
@all-contributors please add @MRslimcoder for content

**Comment by AvidCoder101** [comment]
@all-contributors please add @CodingSpecies for projectManagement, code, content, doc, review

**Comment by AvidCoder101** [comment]
@all-contributors please add @AvidCoder101 for review

**Comment by MRslimcoder** [comment]
@AvidCoder101 can you please invite me to this organization.

**Comment by CodingSpecies** [comment]
I have sent an invite @MRslimcoder

**Pull request merged**
